-- ANIMAL_INS : 동물 보호소에 들어온 동물의 정보를 담은 테이블
-- ANIMAL_OUTS : 테이블은 동물 보호소에서 입양 보낸 동물
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME
LIMIT 3
;