-- 코드를 입력하세요
-- 중고 거래 게시판 정보 : USED_GOODS_BOARD
-- 중고 거래 게시판 사용자 정보 : USED_GOODS_USER

SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD AS A
LEFT JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS='DONE'
GROUP BY B.USER_ID
HAVING  SUM(A.PRICE) >=700000
ORDER BY TOTAL_SALES;