-- 코드를 입력하세요
SELECT 
    CASE 
        WHEN(SUBSTRING(DATE_FORMAT(DATETIME, '%H'), 1, 1) = 0) 
        THEN SUBSTRING(DATE_FORMAT(DATETIME, '%H'), 2, 1)
        ELSE DATE_FORMAT(DATETIME, "%H") 
    END AS 'HOUR',
COUNT('HOUR') AS 'COUNT'
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H')>=9 AND DATE_FORMAT(DATETIME,'%H')<=19
AND DATE_FORMAT(DATETIME,'%i')<=59
GROUP BY `HOUR`
ORDER BY DATE_FORMAT(DATETIME, '%H');
